package com.mengya.bean;

import java.util.Date;


public class HxServiceRetreatReplacement{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.apply_id
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String applyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.sequence
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private Integer sequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.apply_unit
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String applyUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.sell_subsection
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String sellSubsection;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.sell_store
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String sellStore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.is_presale
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String isPresale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.is_onwall
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String isOnwall;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.customer_name
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String customerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.customer_phone
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String customerPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.customer_address
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String customerAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.buy_date
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private Date buyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.fault_date
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private Date faultDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.retreat_replacement
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String retreatReplacement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.rr_mode
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String rrMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.fault_code
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String faultCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.fault_reason
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String faultReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.fault_reason_detail
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String faultReasonDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.install_unit
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String installUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.install_date
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private Date installDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.intaller
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String intaller;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.delivery_order_num
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String deliveryOrderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.old_machine_type
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String oldMachineType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.old_gome_code
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String oldGomeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.old_brand
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String oldBrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.old_machine_code
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String oldMachineCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.old_inner_code1
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String oldInnerCode1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.old_inner_code2
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String oldInnerCode2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.old_outer_code
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String oldOuterCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.machine_type
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String machineType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.gome_code
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String gomeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.brand
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String brand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.machine_code
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String machineCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.inner_code1
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String innerCode1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.inner_code2
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String innerCode2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.outer_code
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String outerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.rr_date
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private Date rrDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.is_ic_back
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String isIcBack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.record_time
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private Date recordTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.status
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.is_stored
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String isStored;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.appraiser
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String appraiser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.check_result
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String checkResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.machine_check_fault_reason
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String machineCheckFaultReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.center_check_result
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String centerCheckResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.center_check_comment
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String centerCheckComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.center_check_man
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String centerCheckMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.center_check_time
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private Date centerCheckTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.headquarters_check_result
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String headquartersCheckResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.headquarters_check_comment
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String headquartersCheckComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.headquarters_check_man
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String headquartersCheckMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.headquarters_check_time
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private Date headquartersCheckTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.create_man
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String createMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.create_organization
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String createOrganization;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.create_time
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.alter_man
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String alterMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.alter_organization
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String alterOrganization;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.alter_time
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private Date alterTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.comment
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.accessory
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String accessory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.process_instance_id
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String processInstanceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.applicant
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String applicant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.apply_date
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private Date applyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.service_unit
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String serviceUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.create_position
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private String createPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_retreat_replacement.is_pass_check
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    private Boolean isPassCheck;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.apply_id
     *
     * @return the value of hx_service_retreat_replacement.apply_id
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getApplyId() {
        return applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.apply_id
     *
     * @param applyId the value for hx_service_retreat_replacement.apply_id
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setApplyId(String applyId) {
        this.applyId = applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.sequence
     *
     * @return the value of hx_service_retreat_replacement.sequence
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.sequence
     *
     * @param sequence the value for hx_service_retreat_replacement.sequence
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.apply_unit
     *
     * @return the value of hx_service_retreat_replacement.apply_unit
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getApplyUnit() {
        return applyUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.apply_unit
     *
     * @param applyUnit the value for hx_service_retreat_replacement.apply_unit
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setApplyUnit(String applyUnit) {
        this.applyUnit = applyUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.sell_subsection
     *
     * @return the value of hx_service_retreat_replacement.sell_subsection
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getSellSubsection() {
        return sellSubsection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.sell_subsection
     *
     * @param sellSubsection the value for hx_service_retreat_replacement.sell_subsection
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setSellSubsection(String sellSubsection) {
        this.sellSubsection = sellSubsection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.sell_store
     *
     * @return the value of hx_service_retreat_replacement.sell_store
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getSellStore() {
        return sellStore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.sell_store
     *
     * @param sellStore the value for hx_service_retreat_replacement.sell_store
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setSellStore(String sellStore) {
        this.sellStore = sellStore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.is_presale
     *
     * @return the value of hx_service_retreat_replacement.is_presale
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getIsPresale() {
        return isPresale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.is_presale
     *
     * @param isPresale the value for hx_service_retreat_replacement.is_presale
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setIsPresale(String isPresale) {
        this.isPresale = isPresale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.is_onwall
     *
     * @return the value of hx_service_retreat_replacement.is_onwall
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getIsOnwall() {
        return isOnwall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.is_onwall
     *
     * @param isOnwall the value for hx_service_retreat_replacement.is_onwall
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setIsOnwall(String isOnwall) {
        this.isOnwall = isOnwall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.customer_name
     *
     * @return the value of hx_service_retreat_replacement.customer_name
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.customer_name
     *
     * @param customerName the value for hx_service_retreat_replacement.customer_name
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.customer_phone
     *
     * @return the value of hx_service_retreat_replacement.customer_phone
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getCustomerPhone() {
        return customerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.customer_phone
     *
     * @param customerPhone the value for hx_service_retreat_replacement.customer_phone
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setCustomerPhone(String customerPhone) {
        this.customerPhone = customerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.customer_address
     *
     * @return the value of hx_service_retreat_replacement.customer_address
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getCustomerAddress() {
        return customerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.customer_address
     *
     * @param customerAddress the value for hx_service_retreat_replacement.customer_address
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setCustomerAddress(String customerAddress) {
        this.customerAddress = customerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.buy_date
     *
     * @return the value of hx_service_retreat_replacement.buy_date
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public Date getBuyDate() {
        return buyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.buy_date
     *
     * @param buyDate the value for hx_service_retreat_replacement.buy_date
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setBuyDate(Date buyDate) {
        this.buyDate = buyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.fault_date
     *
     * @return the value of hx_service_retreat_replacement.fault_date
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public Date getFaultDate() {
        return faultDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.fault_date
     *
     * @param faultDate the value for hx_service_retreat_replacement.fault_date
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setFaultDate(Date faultDate) {
        this.faultDate = faultDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.retreat_replacement
     *
     * @return the value of hx_service_retreat_replacement.retreat_replacement
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getRetreatReplacement() {
        return retreatReplacement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.retreat_replacement
     *
     * @param retreatReplacement the value for hx_service_retreat_replacement.retreat_replacement
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setRetreatReplacement(String retreatReplacement) {
        this.retreatReplacement = retreatReplacement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.rr_mode
     *
     * @return the value of hx_service_retreat_replacement.rr_mode
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getRrMode() {
        return rrMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.rr_mode
     *
     * @param rrMode the value for hx_service_retreat_replacement.rr_mode
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setRrMode(String rrMode) {
        this.rrMode = rrMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.fault_code
     *
     * @return the value of hx_service_retreat_replacement.fault_code
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getFaultCode() {
        return faultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.fault_code
     *
     * @param faultCode the value for hx_service_retreat_replacement.fault_code
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setFaultCode(String faultCode) {
        this.faultCode = faultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.fault_reason
     *
     * @return the value of hx_service_retreat_replacement.fault_reason
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getFaultReason() {
        return faultReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.fault_reason
     *
     * @param faultReason the value for hx_service_retreat_replacement.fault_reason
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setFaultReason(String faultReason) {
        this.faultReason = faultReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.fault_reason_detail
     *
     * @return the value of hx_service_retreat_replacement.fault_reason_detail
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getFaultReasonDetail() {
        return faultReasonDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.fault_reason_detail
     *
     * @param faultReasonDetail the value for hx_service_retreat_replacement.fault_reason_detail
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setFaultReasonDetail(String faultReasonDetail) {
        this.faultReasonDetail = faultReasonDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.install_unit
     *
     * @return the value of hx_service_retreat_replacement.install_unit
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getInstallUnit() {
        return installUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.install_unit
     *
     * @param installUnit the value for hx_service_retreat_replacement.install_unit
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setInstallUnit(String installUnit) {
        this.installUnit = installUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.install_date
     *
     * @return the value of hx_service_retreat_replacement.install_date
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public Date getInstallDate() {
        return installDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.install_date
     *
     * @param installDate the value for hx_service_retreat_replacement.install_date
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setInstallDate(Date installDate) {
        this.installDate = installDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.intaller
     *
     * @return the value of hx_service_retreat_replacement.intaller
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getIntaller() {
        return intaller;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.intaller
     *
     * @param intaller the value for hx_service_retreat_replacement.intaller
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setIntaller(String intaller) {
        this.intaller = intaller;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.delivery_order_num
     *
     * @return the value of hx_service_retreat_replacement.delivery_order_num
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getDeliveryOrderNum() {
        return deliveryOrderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.delivery_order_num
     *
     * @param deliveryOrderNum the value for hx_service_retreat_replacement.delivery_order_num
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setDeliveryOrderNum(String deliveryOrderNum) {
        this.deliveryOrderNum = deliveryOrderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.old_machine_type
     *
     * @return the value of hx_service_retreat_replacement.old_machine_type
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getOldMachineType() {
        return oldMachineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.old_machine_type
     *
     * @param oldMachineType the value for hx_service_retreat_replacement.old_machine_type
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setOldMachineType(String oldMachineType) {
        this.oldMachineType = oldMachineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.old_gome_code
     *
     * @return the value of hx_service_retreat_replacement.old_gome_code
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getOldGomeCode() {
        return oldGomeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.old_gome_code
     *
     * @param oldGomeCode the value for hx_service_retreat_replacement.old_gome_code
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setOldGomeCode(String oldGomeCode) {
        this.oldGomeCode = oldGomeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.old_brand
     *
     * @return the value of hx_service_retreat_replacement.old_brand
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getOldBrand() {
        return oldBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.old_brand
     *
     * @param oldBrand the value for hx_service_retreat_replacement.old_brand
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setOldBrand(String oldBrand) {
        this.oldBrand = oldBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.old_machine_code
     *
     * @return the value of hx_service_retreat_replacement.old_machine_code
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getOldMachineCode() {
        return oldMachineCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.old_machine_code
     *
     * @param oldMachineCode the value for hx_service_retreat_replacement.old_machine_code
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setOldMachineCode(String oldMachineCode) {
        this.oldMachineCode = oldMachineCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.old_inner_code1
     *
     * @return the value of hx_service_retreat_replacement.old_inner_code1
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getOldInnerCode1() {
        return oldInnerCode1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.old_inner_code1
     *
     * @param oldInnerCode1 the value for hx_service_retreat_replacement.old_inner_code1
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setOldInnerCode1(String oldInnerCode1) {
        this.oldInnerCode1 = oldInnerCode1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.old_inner_code2
     *
     * @return the value of hx_service_retreat_replacement.old_inner_code2
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getOldInnerCode2() {
        return oldInnerCode2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.old_inner_code2
     *
     * @param oldInnerCode2 the value for hx_service_retreat_replacement.old_inner_code2
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setOldInnerCode2(String oldInnerCode2) {
        this.oldInnerCode2 = oldInnerCode2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.old_outer_code
     *
     * @return the value of hx_service_retreat_replacement.old_outer_code
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getOldOuterCode() {
        return oldOuterCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.old_outer_code
     *
     * @param oldOuterCode the value for hx_service_retreat_replacement.old_outer_code
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setOldOuterCode(String oldOuterCode) {
        this.oldOuterCode = oldOuterCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.machine_type
     *
     * @return the value of hx_service_retreat_replacement.machine_type
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getMachineType() {
        return machineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.machine_type
     *
     * @param machineType the value for hx_service_retreat_replacement.machine_type
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setMachineType(String machineType) {
        this.machineType = machineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.gome_code
     *
     * @return the value of hx_service_retreat_replacement.gome_code
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getGomeCode() {
        return gomeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.gome_code
     *
     * @param gomeCode the value for hx_service_retreat_replacement.gome_code
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setGomeCode(String gomeCode) {
        this.gomeCode = gomeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.brand
     *
     * @return the value of hx_service_retreat_replacement.brand
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.brand
     *
     * @param brand the value for hx_service_retreat_replacement.brand
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.machine_code
     *
     * @return the value of hx_service_retreat_replacement.machine_code
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getMachineCode() {
        return machineCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.machine_code
     *
     * @param machineCode the value for hx_service_retreat_replacement.machine_code
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setMachineCode(String machineCode) {
        this.machineCode = machineCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.inner_code1
     *
     * @return the value of hx_service_retreat_replacement.inner_code1
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getInnerCode1() {
        return innerCode1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.inner_code1
     *
     * @param innerCode1 the value for hx_service_retreat_replacement.inner_code1
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setInnerCode1(String innerCode1) {
        this.innerCode1 = innerCode1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.inner_code2
     *
     * @return the value of hx_service_retreat_replacement.inner_code2
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getInnerCode2() {
        return innerCode2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.inner_code2
     *
     * @param innerCode2 the value for hx_service_retreat_replacement.inner_code2
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setInnerCode2(String innerCode2) {
        this.innerCode2 = innerCode2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.outer_code
     *
     * @return the value of hx_service_retreat_replacement.outer_code
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getOuterCode() {
        return outerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.outer_code
     *
     * @param outerCode the value for hx_service_retreat_replacement.outer_code
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setOuterCode(String outerCode) {
        this.outerCode = outerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.rr_date
     *
     * @return the value of hx_service_retreat_replacement.rr_date
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public Date getRrDate() {
        return rrDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.rr_date
     *
     * @param rrDate the value for hx_service_retreat_replacement.rr_date
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setRrDate(Date rrDate) {
        this.rrDate = rrDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.is_ic_back
     *
     * @return the value of hx_service_retreat_replacement.is_ic_back
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getIsIcBack() {
        return isIcBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.is_ic_back
     *
     * @param isIcBack the value for hx_service_retreat_replacement.is_ic_back
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setIsIcBack(String isIcBack) {
        this.isIcBack = isIcBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.record_time
     *
     * @return the value of hx_service_retreat_replacement.record_time
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public Date getRecordTime() {
        return recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.record_time
     *
     * @param recordTime the value for hx_service_retreat_replacement.record_time
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setRecordTime(Date recordTime) {
        this.recordTime = recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.status
     *
     * @return the value of hx_service_retreat_replacement.status
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.status
     *
     * @param status the value for hx_service_retreat_replacement.status
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.is_stored
     *
     * @return the value of hx_service_retreat_replacement.is_stored
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getIsStored() {
        return isStored;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.is_stored
     *
     * @param isStored the value for hx_service_retreat_replacement.is_stored
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setIsStored(String isStored) {
        this.isStored = isStored;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.appraiser
     *
     * @return the value of hx_service_retreat_replacement.appraiser
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getAppraiser() {
        return appraiser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.appraiser
     *
     * @param appraiser the value for hx_service_retreat_replacement.appraiser
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setAppraiser(String appraiser) {
        this.appraiser = appraiser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.check_result
     *
     * @return the value of hx_service_retreat_replacement.check_result
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getCheckResult() {
        return checkResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.check_result
     *
     * @param checkResult the value for hx_service_retreat_replacement.check_result
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setCheckResult(String checkResult) {
        this.checkResult = checkResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.machine_check_fault_reason
     *
     * @return the value of hx_service_retreat_replacement.machine_check_fault_reason
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getMachineCheckFaultReason() {
        return machineCheckFaultReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.machine_check_fault_reason
     *
     * @param machineCheckFaultReason the value for hx_service_retreat_replacement.machine_check_fault_reason
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setMachineCheckFaultReason(String machineCheckFaultReason) {
        this.machineCheckFaultReason = machineCheckFaultReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.center_check_result
     *
     * @return the value of hx_service_retreat_replacement.center_check_result
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getCenterCheckResult() {
        return centerCheckResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.center_check_result
     *
     * @param centerCheckResult the value for hx_service_retreat_replacement.center_check_result
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setCenterCheckResult(String centerCheckResult) {
        this.centerCheckResult = centerCheckResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.center_check_comment
     *
     * @return the value of hx_service_retreat_replacement.center_check_comment
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getCenterCheckComment() {
        return centerCheckComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.center_check_comment
     *
     * @param centerCheckComment the value for hx_service_retreat_replacement.center_check_comment
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setCenterCheckComment(String centerCheckComment) {
        this.centerCheckComment = centerCheckComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.center_check_man
     *
     * @return the value of hx_service_retreat_replacement.center_check_man
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getCenterCheckMan() {
        return centerCheckMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.center_check_man
     *
     * @param centerCheckMan the value for hx_service_retreat_replacement.center_check_man
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setCenterCheckMan(String centerCheckMan) {
        this.centerCheckMan = centerCheckMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.center_check_time
     *
     * @return the value of hx_service_retreat_replacement.center_check_time
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public Date getCenterCheckTime() {
        return centerCheckTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.center_check_time
     *
     * @param centerCheckTime the value for hx_service_retreat_replacement.center_check_time
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setCenterCheckTime(Date centerCheckTime) {
        this.centerCheckTime = centerCheckTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.headquarters_check_result
     *
     * @return the value of hx_service_retreat_replacement.headquarters_check_result
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getHeadquartersCheckResult() {
        return headquartersCheckResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.headquarters_check_result
     *
     * @param headquartersCheckResult the value for hx_service_retreat_replacement.headquarters_check_result
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setHeadquartersCheckResult(String headquartersCheckResult) {
        this.headquartersCheckResult = headquartersCheckResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.headquarters_check_comment
     *
     * @return the value of hx_service_retreat_replacement.headquarters_check_comment
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getHeadquartersCheckComment() {
        return headquartersCheckComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.headquarters_check_comment
     *
     * @param headquartersCheckComment the value for hx_service_retreat_replacement.headquarters_check_comment
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setHeadquartersCheckComment(String headquartersCheckComment) {
        this.headquartersCheckComment = headquartersCheckComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.headquarters_check_man
     *
     * @return the value of hx_service_retreat_replacement.headquarters_check_man
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getHeadquartersCheckMan() {
        return headquartersCheckMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.headquarters_check_man
     *
     * @param headquartersCheckMan the value for hx_service_retreat_replacement.headquarters_check_man
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setHeadquartersCheckMan(String headquartersCheckMan) {
        this.headquartersCheckMan = headquartersCheckMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.headquarters_check_time
     *
     * @return the value of hx_service_retreat_replacement.headquarters_check_time
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public Date getHeadquartersCheckTime() {
        return headquartersCheckTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.headquarters_check_time
     *
     * @param headquartersCheckTime the value for hx_service_retreat_replacement.headquarters_check_time
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setHeadquartersCheckTime(Date headquartersCheckTime) {
        this.headquartersCheckTime = headquartersCheckTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.create_man
     *
     * @return the value of hx_service_retreat_replacement.create_man
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getCreateMan() {
        return createMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.create_man
     *
     * @param createMan the value for hx_service_retreat_replacement.create_man
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setCreateMan(String createMan) {
        this.createMan = createMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.create_organization
     *
     * @return the value of hx_service_retreat_replacement.create_organization
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getCreateOrganization() {
        return createOrganization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.create_organization
     *
     * @param createOrganization the value for hx_service_retreat_replacement.create_organization
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setCreateOrganization(String createOrganization) {
        this.createOrganization = createOrganization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.create_time
     *
     * @return the value of hx_service_retreat_replacement.create_time
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.create_time
     *
     * @param createTime the value for hx_service_retreat_replacement.create_time
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.alter_man
     *
     * @return the value of hx_service_retreat_replacement.alter_man
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getAlterMan() {
        return alterMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.alter_man
     *
     * @param alterMan the value for hx_service_retreat_replacement.alter_man
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setAlterMan(String alterMan) {
        this.alterMan = alterMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.alter_organization
     *
     * @return the value of hx_service_retreat_replacement.alter_organization
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getAlterOrganization() {
        return alterOrganization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.alter_organization
     *
     * @param alterOrganization the value for hx_service_retreat_replacement.alter_organization
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setAlterOrganization(String alterOrganization) {
        this.alterOrganization = alterOrganization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.alter_time
     *
     * @return the value of hx_service_retreat_replacement.alter_time
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public Date getAlterTime() {
        return alterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.alter_time
     *
     * @param alterTime the value for hx_service_retreat_replacement.alter_time
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setAlterTime(Date alterTime) {
        this.alterTime = alterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.comment
     *
     * @return the value of hx_service_retreat_replacement.comment
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.comment
     *
     * @param comment the value for hx_service_retreat_replacement.comment
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.accessory
     *
     * @return the value of hx_service_retreat_replacement.accessory
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getAccessory() {
        return accessory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.accessory
     *
     * @param accessory the value for hx_service_retreat_replacement.accessory
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setAccessory(String accessory) {
        this.accessory = accessory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.process_instance_id
     *
     * @return the value of hx_service_retreat_replacement.process_instance_id
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getProcessInstanceId() {
        return processInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.process_instance_id
     *
     * @param processInstanceId the value for hx_service_retreat_replacement.process_instance_id
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setProcessInstanceId(String processInstanceId) {
        this.processInstanceId = processInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.applicant
     *
     * @return the value of hx_service_retreat_replacement.applicant
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getApplicant() {
        return applicant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.applicant
     *
     * @param applicant the value for hx_service_retreat_replacement.applicant
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setApplicant(String applicant) {
        this.applicant = applicant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.apply_date
     *
     * @return the value of hx_service_retreat_replacement.apply_date
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public Date getApplyDate() {
        return applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.apply_date
     *
     * @param applyDate the value for hx_service_retreat_replacement.apply_date
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setApplyDate(Date applyDate) {
        this.applyDate = applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.service_unit
     *
     * @return the value of hx_service_retreat_replacement.service_unit
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getServiceUnit() {
        return serviceUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.service_unit
     *
     * @param serviceUnit the value for hx_service_retreat_replacement.service_unit
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setServiceUnit(String serviceUnit) {
        this.serviceUnit = serviceUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.create_position
     *
     * @return the value of hx_service_retreat_replacement.create_position
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public String getCreatePosition() {
        return createPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.create_position
     *
     * @param createPosition the value for hx_service_retreat_replacement.create_position
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setCreatePosition(String createPosition) {
        this.createPosition = createPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_retreat_replacement.is_pass_check
     *
     * @return the value of hx_service_retreat_replacement.is_pass_check
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public Boolean getIsPassCheck() {
        return isPassCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_retreat_replacement.is_pass_check
     *
     * @param isPassCheck the value for hx_service_retreat_replacement.is_pass_check
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    public void setIsPassCheck(Boolean isPassCheck) {
        this.isPassCheck = isPassCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hx_service_retreat_replacement
     *
     * @mbggenerated Wed Nov 19 17:37:27 CST 2014
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", applyId=").append(applyId);
        sb.append(", sequence=").append(sequence);
        sb.append(", applyUnit=").append(applyUnit);
        sb.append(", sellSubsection=").append(sellSubsection);
        sb.append(", sellStore=").append(sellStore);
        sb.append(", isPresale=").append(isPresale);
        sb.append(", isOnwall=").append(isOnwall);
        sb.append(", customerName=").append(customerName);
        sb.append(", customerPhone=").append(customerPhone);
        sb.append(", customerAddress=").append(customerAddress);
        sb.append(", buyDate=").append(buyDate);
        sb.append(", faultDate=").append(faultDate);
        sb.append(", retreatReplacement=").append(retreatReplacement);
        sb.append(", rrMode=").append(rrMode);
        sb.append(", faultCode=").append(faultCode);
        sb.append(", faultReason=").append(faultReason);
        sb.append(", faultReasonDetail=").append(faultReasonDetail);
        sb.append(", installUnit=").append(installUnit);
        sb.append(", installDate=").append(installDate);
        sb.append(", intaller=").append(intaller);
        sb.append(", deliveryOrderNum=").append(deliveryOrderNum);
        sb.append(", oldMachineType=").append(oldMachineType);
        sb.append(", oldGomeCode=").append(oldGomeCode);
        sb.append(", oldBrand=").append(oldBrand);
        sb.append(", oldMachineCode=").append(oldMachineCode);
        sb.append(", oldInnerCode1=").append(oldInnerCode1);
        sb.append(", oldInnerCode2=").append(oldInnerCode2);
        sb.append(", oldOuterCode=").append(oldOuterCode);
        sb.append(", machineType=").append(machineType);
        sb.append(", gomeCode=").append(gomeCode);
        sb.append(", brand=").append(brand);
        sb.append(", machineCode=").append(machineCode);
        sb.append(", innerCode1=").append(innerCode1);
        sb.append(", innerCode2=").append(innerCode2);
        sb.append(", outerCode=").append(outerCode);
        sb.append(", rrDate=").append(rrDate);
        sb.append(", isIcBack=").append(isIcBack);
        sb.append(", recordTime=").append(recordTime);
        sb.append(", status=").append(status);
        sb.append(", isStored=").append(isStored);
        sb.append(", appraiser=").append(appraiser);
        sb.append(", checkResult=").append(checkResult);
        sb.append(", machineCheckFaultReason=").append(machineCheckFaultReason);
        sb.append(", centerCheckResult=").append(centerCheckResult);
        sb.append(", centerCheckComment=").append(centerCheckComment);
        sb.append(", centerCheckMan=").append(centerCheckMan);
        sb.append(", centerCheckTime=").append(centerCheckTime);
        sb.append(", headquartersCheckResult=").append(headquartersCheckResult);
        sb.append(", headquartersCheckComment=").append(headquartersCheckComment);
        sb.append(", headquartersCheckMan=").append(headquartersCheckMan);
        sb.append(", headquartersCheckTime=").append(headquartersCheckTime);
        sb.append(", createMan=").append(createMan);
        sb.append(", createOrganization=").append(createOrganization);
        sb.append(", createTime=").append(createTime);
        sb.append(", alterMan=").append(alterMan);
        sb.append(", alterOrganization=").append(alterOrganization);
        sb.append(", alterTime=").append(alterTime);
        sb.append(", comment=").append(comment);
        sb.append(", accessory=").append(accessory);
        sb.append(", processInstanceId=").append(processInstanceId);
        sb.append(", applicant=").append(applicant);
        sb.append(", applyDate=").append(applyDate);
        sb.append(", serviceUnit=").append(serviceUnit);
        sb.append(", createPosition=").append(createPosition);
        sb.append(", isPassCheck=").append(isPassCheck);
        sb.append("]");
        return sb.toString();
    }

}